[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Infinitus Ministries"
authors = [{name = "Willow", email = "7dz26lnlt@mozmail.com"}]
dynamic = ["version", "description"]
